---
name: build-deploy
kind: pipeline

trigger:
  branch:
    - master

steps:
  - name: build host-proxy
    image: plugins/docker
    settings:
      repo: "tsingjyujing/host-proxy"
      use_cache: true
      cache_from: "tsingjyujing/host-proxy"
      username:
        from_secret: docker_user
      password:
        from_secret: docker_password
      context: host-proxy
      dockerfile: host-proxy/Dockerfile
      tags:
        - latest

  - name: build mysql-lite-5
    image: plugins/docker
    settings:
      repo: "tsingjyujing/mysql-lite"
      use_cache: true
      cache_from: "tsingjyujing/mysql-lite:5"
      username:
        from_secret: docker_user
      password:
        from_secret: docker_password
      context: mysql-lite
      dockerfile: mysql-lite/Dockerfile.5
      tags:
        - 5
        
  - name: build mysql-lite-8
    image: plugins/docker
    settings:
      repo: "tsingjyujing/mysql-lite"
      use_cache: true
      cache_from: "tsingjyujing/mysql-lite:8"
      username:
        from_secret: docker_user
      password:
        from_secret: docker_password
      context: mysql-lite
      dockerfile: mysql-lite/Dockerfile.8
      tags:
        - 8