name: Docker Image CI

on:
  push:
    branches: master

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push (Host Proxy)
        uses: docker/build-push-action@v2
        with:
          context: host-proxy
          file: host-proxy/Dockerfile 
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: tsingjyujing/host-proxy:latest
      -
        name: Build and push (MySQL v5)
        uses: docker/build-push-action@v2
        with:
          context: mysql-lite
          file: mysql-lite/Dockerfile.5
          platforms: linux/amd64
          push: true
          tags: tsingjyujing/mysql-lite:latest
      -
        name: Build and push (MySQL v8)
        uses: docker/build-push-action@v2
        with:
          context: mysql-lite
          file: mysql-lite/Dockerfile.8
          platforms: linux/amd64
          push: true
          tags: tsingjyujing/mysql-lite:latest 
